### PR TITLE
Get all matching issues for a query

### PR DESCRIPTION
**Pull request by junichi11**
PR for #35

### CODE REVIEW

**Comment by DrSchranz** [comment]
Now I'm able to list much more issues with this change, its great.

When querying large amounts of issues I have some worries about downloading all issues at once. And I tend to think about paging the results. 
But I think that paging only can be implemented in "QueryPanel", I don't see a way to implement it on the QueryProvider / QueryProvider.IssueContainer that feeds the Tasks window. If at least Tasks window will list a discrete amount, but show that there are more results, one can go to the panel again to browse the large amounts. But I don't see how, so paging doesn't help much here.

What I think that will be possible easy, is to run `QueryPanel.search()` in parallel to show an indeterminate `ProgressHandle` (or maybe with just components in the panel ) in order to
to justify delay before the results. (Netbeans is sometimes worrying about the delay )
What do you think?

**Comment by junichi11** [comment]
> When querying large amounts of issues I have some worries about downloading all issues at once. And I tend to think about paging the results. 
> But I think that paging only can be implemented in "QueryPanel", I don't see a way to implement it on the QueryProvider / QueryProvider.IssueContainer that feeds the Tasks window. If at least Tasks window will list a discrete amount, but show that there are more results, one can go to the panel again to browse the large amounts. But I don't see how, so paging doesn't help much here.

Shown issues in Task window are restricted. We can change that in the Options (Tools > Options > Team > Task). 

> What I think that will be easy, is to run QueryPanel.search() in parallel to show an indeterminate ProgressHandle (or maybe with just components in the panel ) and
> justify the delay before the results. (Netbeans is sometimes worrying about the delay )

Currently, my code is so bad. NetBeans may be freezed a bit. So I'll use RP and Progress Bar. Then disable some components while searching issues.

**Comment by junichi11** [comment]
a nbm for testing:
https://github.com/junichi11/netbeans-backlog-plugin/releases/tag/v0.3.3https://github.com/junichi11/netbeans-backlog-plugin/releases/tag/v0.3.3 (0.3.3.2-dev)

**Comment by DrSchranz** [comment]
It works and looks good for me!
BTW. I was wondering how the task on RP could be stopped, thanks!

**Comment by junichi11** [comment]
I've add a few improvements. An Issue count to get can be restrict. If there are no problems, I'll release a new version ;)
https://github.com/junichi11/netbeans-backlog-plugin/releases/tag/v0.3.3 0.3.3.3-dev

**Comment by DrSchranz** [comment]
I've checked this features, and liked to control the amount of issues requested. 
One can create a big saved query, but fetch only a discrete amount to save it for the Tasks window.

There's only one thing when requesting large amounts that is preventing from fetching more than 100, I've noted approximately where I think the issue occurs. 

The rest seems ok, i've saved some queries with this new parameter. And found it useful. Like "All recent tasks, up to ..."
I like this release, thanks!

**Comment by junichi11** [comment]
@DrSchranz Thanks a lot for your comments and testing it!

**Pull request merged**
